apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  # Key-value pairs for environment variables
  DB_URL: 'jdbc:postgresql://host.docker.internal:5432/shop'
  KAFKA_URL: 'host.docker.internal:9092'
  ADDRESS_GROUP_ID: 'shop_address'
  PRODUCT_GROUP_ID: 'shop_product'
  PRODUCT_CATEGORY_GROUP_ID: 'shop_product_category'
  STORE_GROUP_ID: 'shop_store'
  STOCK_GROUP_ID: 'shop_stock'
  ORDER_GROUP_ID: 'shop_order'
  SAVER_GROUP_ID: 'shop_saver'
  UPDATER_GROUP_ID: 'shop_updater'
  OPERATION_GROUP_ID: 'shop_operation'
  NOTIFICATION_GROUP_ID: 'shop_notification'
  PAYMENT_GROUP_ID: 'shop_payment'
  SHIPMENT_GROUP_ID: 'shop_shipment'
  REDIS_HOST: 'host.docker.internal'
  REDIS_PORT: '6379'
  REDIS_PASS: '1234'
  KEYCLOAK_URL: 'http://host.docker.internal:8180'
  KEYCLOAK_REALM: 'shop'
  BASE_URL: 'http://host.docker.internal'
  OPERATION_SERVICE_PORT: '9086'
  RECEIPT_EXPIRATION_MINUTES: '360'
  MESSAGE_TTL_SECONDS: '3600'
  CONFIG_SERVER_URL: 'http://config-server-service:8888'
  CONFIG_SERVER_PORT: '8888'
  EUREKA_HOST_NAME: 'eureka-server-service'
  EUREKA_PORT: '8761'
  ADDRESS_MODULE_NAME: 'address'
  PRODUCT_MODULE_NAME: 'product'
  PRODUCT_CATEGORY_MODULE_NAME: 'product-category'
  STORE_MODULE_NAME: 'store'
  STOCK_MODULE_NAME: 'stock'
  ORDER_MODULE_NAME: 'order'
  OPERATION_MODULE_NAME: 'operation'
  PAYMENT_MODULE_NAME: 'payment'
  SHIPMENT_MODULE_NAME: 'shipment'
  SHOP_NOTIFIER_MODULE_NAME: 'notification'
  GATE_MODULE_NAME: 'gate'