apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  DB_PASS: '1999'
  DB_USER: 'postgres'
  KEYCLOAK_USERNAME: 'shop_admin'
  KEYCLOAK_PASSWORD: 'admin'
  KEYCLOAK_CLIENT_ID: 'shop-app'
  KEYCLOAK_CLIENT_SECRET: 'twTHxYDIAytva0qDG0GvYXmboSvQtbC4'